## Data Cleaning Project

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
df = pd.read_csv('E:/Data Analytics Python Projects/Pandas Project/Pandas/Airbnb_Open_Data.csv' , dtype= 'unicode' )

In [4]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10,9,10/19/2021,0.21,4,6,286,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30,45,5/21/2022,0.38,4,2,228,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,...,$124,3,0,NaN,NaN,5,1,352,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30,270,7/5/2019,4.64,4,1,322,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10,9,11/19/2018,0.1,3,1,289,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1,0,NaN,NaN,3,1,227,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.8046,-73.96545,United States,...,$167,1,1,7/6/2015,0.02,2,2,395,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3,0,NaN,NaN,5,1,342,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2,5,10/11/2015,0.1,3,1,386,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1,0,NaN,NaN,3,1,69,NaN,NaN

In [5]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10,9,10/19/2021,0.21,4,6,286,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30,45,5/21/2022,0.38,4,2,228,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,...,$124,3,0,NaN,NaN,5,1,352,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30,270,7/5/2019,4.64,4,1,322,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10,9,11/19/2018,0.1,3,1,289,"Please no smoking in the house, porch or on th...",NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  object
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  object
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  object
 8   long                            102591 non-null  object
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  object
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  object
 18  number of reviews               102416 non-null  object
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   object
 21  review rate number              102273 non-null  object
 22  calculated host listings count  102280 non-null  object
 23  availability 365                102151 non-null  object
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: object(26)
memory usage: 20.4+ MB

In [7]:
df["license"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
102594    NaN
102595    NaN
102596    NaN
102597    NaN
102598    NaN
Name: license, Length: 102599, dtype: object

#### Deleting redundant columns

In [8]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [9]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'] 

columns_to_drop = ['id','reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

In [10]:
len(columns_to_keep)

19

In [11]:
len(columns_to_drop)

7

##### Filtering Data

In [12]:
df[columns_to_keep]

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,$966,$193,10,9,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2007,$142,$28,30,45,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,US,TRUE,flexible,Private room,2005,$620,$124,3,0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,TRUE,moderate,Entire home/apt,2005,$368,$74,30,270,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,$204,$41,10,9,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,FALSE,flexible,Private room,2003,$844,$169,1,0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.8046,-73.96545,United States,US,TRUE,moderate,Private room,2016,$837,$167,1,1,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,TRUE,moderate,Private room,2009,$988,$198,3,0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,TRUE,strict,Entire home/apt,2015,$546,$109,2,5,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,FALSE,flexible,Entire home/apt,2010,"$1,032",$206,1,0,NaN

In [13]:
df.shape

(102599, 26)

In [14]:
df1 = df.drop(columns= columns_to_drop)

In [15]:
df1

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,$966,$193,10,9,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2007,$142,$28,30,45,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,US,TRUE,flexible,Private room,2005,$620,$124,3,0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,TRUE,moderate,Entire home/apt,2005,$368,$74,30,270,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,$204,$41,10,9,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,FALSE,flexible,Private room,2003,$844,$169,1,0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.8046,-73.96545,United States,US,TRUE,moderate,Private room,2016,$837,$167,1,1,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,TRUE,moderate,Private room,2009,$988,$198,3,0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,TRUE,strict,Entire home/apt,2015,$546,$109,2,5,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,FALSE,flexible,Entire home/apt,2010,"$1,032",$206,1,0,NaN

In [16]:
df1.shape

(102599, 19)

In [17]:
df1.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

##### Renaming the columns

In [18]:
df1.rename(columns = {'NAME' : 'Name'} , inplace=True)

In [19]:
df1.head()

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,$966,$193,10,9,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2007,$142,$28,30,45,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,US,TRUE,flexible,Private room,2005,$620,$124,3,0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,TRUE,moderate,Entire home/apt,2005,$368,$74,30,270,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,$204,$41,10,9,11/19/2018

In [20]:
# Converting column names in lower case

new_column_name = []
for i in df1.columns:
    new_column_name.append(i.lower())

In [21]:
new_column_name

['name',
 'host id',
 'host_identity_verified',
 'host name',
 'neighbourhood group',
 'neighbourhood',
 'lat',
 'long',
 'country',
 'country code',
 'instant_bookable',
 'cancellation_policy',
 'room type',
 'construction year',
 'price',
 'service fee',
 'minimum nights',
 'number of reviews',
 'last review']

In [22]:
# Naming columns with upper case
df1.columns = new_column_name

In [23]:
df1.head()

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,$966,$193,10,9,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2007,$142,$28,30,45,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,US,TRUE,flexible,Private room,2005,$620,$124,3,0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,TRUE,moderate,Entire home/apt,2005,$368,$74,30,270,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,$204,$41,10,9,11/19/2018

##### Checking Duplicate data

In [24]:
df1.duplicated().sum()

np.int64(541)

In [25]:
# Drop duplicates
df1.drop_duplicates(inplace= True)

In [26]:
df1.duplicated().sum()

np.int64(0)

##### Removing NaN values

In [27]:
df1.isna().sum()

name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [28]:
df1.drop(columns= ['last review'] , inplace= True)

In [29]:
df1.isna().sum()

name                      250
host id                     0
host_identity_verified    289
host name                 404
neighbourhood group        29
neighbourhood              16
lat                         8
long                        8
country                   532
country code              131
instant_bookable          105
cancellation_policy        76
room type                   0
construction year         214
price                     247
service fee               273
minimum nights            400
number of reviews         183
dtype: int64

##### Dropping NaN

In [30]:
df1.dropna(inplace= True)

In [31]:
df1.isna().sum()

name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
dtype: int64

##### Cleanig individual columns

In [32]:
df1

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,$966,$193,10,9
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2007,$142,$28,30,45
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,$204,$41,10,9
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,TRUE,flexible,Entire home/apt,2013,$577,$115,3,74
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,FALSE,moderate,Private room,2009,"$1,060",$212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,FALSE,flexible,Private room,2018,$822,$164,1,9
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,TRUE,moderate,Private room,2015,$455,$91,4,36
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.7087,-73.9671,United States,US,TRUE,flexible,Private room,2020,"$1,078",$216,1,58
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,FALSE,moderate,Private room,2007,$103,$21,7,40
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,TRUE,strict,Private room,2022,$982,$196,1,239

In [33]:
df1["host_identity_verified"] = df1.host_identity_verified.str.capitalize()   # Converting "host_identity_verified" in Capitalized

In [34]:
df1

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,$966,$193,10,9
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2007,$142,$28,30,45
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,$204,$41,10,9
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,TRUE,flexible,Entire home/apt,2013,$577,$115,3,74
7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,FALSE,moderate,Private room,2009,"$1,060",$212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,Unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,FALSE,flexible,Private room,2018,$822,$164,1,9
102030,An East Williamsburg Delight,71564706996,Verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,TRUE,moderate,Private room,2015,$455,$91,4,36
102031,Cozy bedroom in williamsburg,83101851929,Verified,Russell,Brooklyn,Williamsburg,40.7087,-73.9671,United States,US,TRUE,flexible,Private room,2020,"$1,078",$216,1,58
102032,Spacious Room w/ 2 Bed,69037598918,Unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,FALSE,moderate,Private room,2007,$103,$21,7,40
102040,"Room in Queens, NY, near LGA.",56457739998,Verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,TRUE,strict,Private room,2022,$982,$196,1,239

In [35]:
df1.head()

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,$966,$193,10,9
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2007,$142,$28,30,45
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,$204,$41,10,9
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,TRUE,flexible,Entire home/apt,2013,$577,$115,3,74
7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,FALSE,moderate,Private room,2009,"$1,060",$212,45,49

In [36]:
df1["instant_bookable"]  # converting False=0 and True=1

0         FALSE
1         FALSE
4         FALSE
5          TRUE
7         FALSE
          ...
102029    FALSE
102030     TRUE
102031     TRUE
102032    FALSE
102040     TRUE
Name: instant_bookable, Length: 99342, dtype: object

In [37]:
df1["instant_bookable"].apply(lambda x : 1 if x == True else 0)

0         0
1         0
4         0
5         0
7         0
         ..
102029    0
102030    0
102031    0
102032    0
102040    0
Name: instant_bookable, Length: 99342, dtype: int64

In [38]:
df1["instant_bookable"] = df1["instant_bookable"].apply(lambda x : 1 if x == True else 0)

In [39]:
df1  # We can observe that index are not in proper sequence

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,$966,$193,10,9
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,$142,$28,30,45
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,$204,$41,10,9
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,0,flexible,Entire home/apt,2013,$577,$115,3,74
7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,"$1,060",$212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,Unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018,$822,$164,1,9
102030,An East Williamsburg Delight,71564706996,Verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,0,moderate,Private room,2015,$455,$91,4,36
102031,Cozy bedroom in williamsburg,83101851929,Verified,Russell,Brooklyn,Williamsburg,40.7087,-73.9671,United States,US,0,flexible,Private room,2020,"$1,078",$216,1,58
102032,Spacious Room w/ 2 Bed,69037598918,Unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007,$103,$21,7,40
102040,"Room in Queens, NY, near LGA.",56457739998,Verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,0,strict,Private room,2022,$982,$196,1,239

In [40]:
# Reseting index
df1.reset_index(inplace= True)

In [41]:
df1

,index,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,$966,$193,10,9
1,1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,$142,$28,30,45
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,$204,$41,10,9
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,0,flexible,Entire home/apt,2013,$577,$115,3,74
4,7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,"$1,060",$212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,Unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018,$822,$164,1,9
99338,102030,An East Williamsburg Delight,71564706996,Verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,0,moderate,Private room,2015,$455,$91,4,36
99339,102031,Cozy bedroom in williamsburg,83101851929,Verified,Russell,Brooklyn,Williamsburg,40.7087,-73.9671,United States,US,0,flexible,Private room,2020,"$1,078",$216,1,58
99340,102032,Spacious Room w/ 2 Bed,69037598918,Unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007,$103,$21,7,40
99341,102040,"Room in Queens, NY, near LGA.",56457739998,Verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,0,strict,Private room,2022,$982,$196,1,239

In [42]:
df1["instant_bookable"].dtype

dtype('int64')

In [43]:
# Removing $ sign from "price" and "service fee". Also converting them into integer
df1["price"] = df1["price"].str.replace("$" , "")

In [44]:
df1["price"]

0          966
1          142
2          204
3          577
4        1,060
          ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: price, Length: 99342, dtype: object

In [45]:
# Removing ','

df1["price"] = df1["price"].str.replace("," , "")

In [46]:
df1["price"]

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: price, Length: 99342, dtype: object

In [47]:
# Removing spaces if any
df1["price"] = df1["price"].str.replace( " " , "")

In [48]:
df1["price"]

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: price, Length: 99342, dtype: object

In [49]:
type(df1["price"])

pandas.core.series.Series

In [50]:
# Now Converting "price" column into integer

df1["price"].astype(int).dtype

dtype('int64')

In [51]:
df1["price"] = df1["price"].astype(int)

In [52]:
df1["price"]

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: price, Length: 99342, dtype: int64

In [53]:
df1["price"].head()

0     966
1     142
2     204
3     577
4    1060
Name: price, dtype: int64

In [54]:
type(df1["price"][1])

numpy.int64

In [55]:
df1.head()

,index,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,$193,10,9
1,1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142,$28,30,45
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204,$41,10,9
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,0,flexible,Entire home/apt,2013,577,$115,3,74
4,7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060,$212,45,49

##### Now cleaning "service fee" as we did for "price" column

In [56]:
df1.head()

,index,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,$193,10,9
1,1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142,$28,30,45
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204,$41,10,9
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,0,flexible,Entire home/apt,2013,577,$115,3,74
4,7,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060,$212,45,49

In [57]:
df1['service fee']

0        $193
1         $28
2         $41
3        $115
4        $212
         ...
99337    $164
99338     $91
99339    $216
99340     $21
99341    $196
Name: service fee, Length: 99342, dtype: object

In [58]:
df1['service fee'] = df1['service fee'].str.replace('$' , '').str.replace(' ' , '')

In [59]:
df1['service fee'] = df1['service fee'].astype(int)

In [60]:
df1['service fee'].dtypes

dtype('int64')

In [67]:
df1.drop(columns= 'index' , inplace= True)

In [68]:
df1

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.975,United States,US,0,flexible,Entire home/apt,2013,577,115,3,74
4,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,Unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018,822,164,1,9
99338,An East Williamsburg Delight,71564706996,Verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,0,moderate,Private room,2015,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,Verified,Russell,Brooklyn,Williamsburg,40.7087,-73.9671,United States,US,0,flexible,Private room,2020,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,Unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,Verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,0,strict,Private room,2022,982,196,1,239

#### Converting cleanead data into csv format

In [69]:
df1.to_csv("Cleaned Data.csv")

In [70]:
pd.read_csv("Cleaned Data.csv")

,Unnamed: 0,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,193,10,9
1,1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142,28,30,45
2,2,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204,41,10,9
3,3,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,0,flexible,Entire home/apt,2013,577,115,3,74
4,4,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,99337,Cozy room in a 2B with backyard access,5155155913,Unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018,822,164,1,9
99338,99338,An East Williamsburg Delight,71564706996,Verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,0,moderate,Private room,2015,455,91,4,36
99339,99339,Cozy bedroom in williamsburg,83101851929,Verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,0,flexible,Private room,2020,1078,216,1,58
99340,99340,Spacious Room w/ 2 Bed,69037598918,Unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007,103,21,7,40
99341,99341,"Room in Queens, NY, near LGA.",56457739998,Verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,0,strict,Private room,2022,982,196,1,239